### ISSUE TITLE
Pull out DockerfileParser to separate python package

### ISSUE THREAD

**Issue by pbabinca** [DBuildService/atomic-reactor#149]
I'd like to parse Dockerfile but I don't want to pull in all the dependencies which dock has. I'm looking at this class: https://github.com/DBuildService/dock/blob/master/dock/util.py#L98.

**Comment by TomasTomecek** [comment]
@shaded-enmity has already some code; we might merge our code with his and make a new upstream project

**Comment by twaugh** [comment]
In #179 I've added a `structure` property to this class as well, for most robust handling of continuation lines and varied-case instruction names. The `get_basename()` and `get_labels()` methods could be reworked to use this.

**Comment by jpopelka** [comment]
> The get_basename() and get_labels() methods could be reworked to use this.

See #180

**Comment by jpopelka** [comment]
There's another one https://github.com/eg0r/dockerfile-parser

**Comment by TomasTomecek** [comment]
@jpopelka look at issues :p

**Comment by jpopelka** [comment]
I've created https://github.com/DBuildService/dockerfile-parser
and moved our DockerfileParser there.
BTW: I'm away till next Tuesday

**Comment by jpopelka** [comment]
I renamed it to [dockerfile-parse](https://github.com/DBuildService/dockerfile-parse) due to name collision with https://github.com/eg0r/dockerfile-parser (which already is on [pypi](https://pypi.python.org/pypi/dockerfile-parser)).
Ideal would be to merge those two (or three: https://github.com/shaded-enmity/dockerfile2json) together.

And as @hhorak pointed out, there's also https://github.com/projectatomic/dockerfile_lint

**Comment by jpopelka** [comment]
dockerfile-parse @ [PyPI](https://pypi.python.org/pypi/dockerfile-parse) and [fedora-review](https://bugzilla.redhat.com/show_bug.cgi?id=1236151)

**Comment by TomasTomecek** [comment]
Neat!! So we are good to get rid of the parsing code in reactor?

**Comment by jpopelka** [comment]
Yes, I'll remove it once we have packages in Fedora/EPEL.
